#
###################################
# Site wide configuration
####################################
#
title: Portfolio & Blog
email: rehanguha29@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Kolkata
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Rehan Guha"
  avatar: leonids-logo.png
  job: "Data Scientist & Machine Learning Engineer"
  bio: ""
  email:
  disqus-shortname:
  twitter: "rehan_guha"#username
  facebook: "rehanguhajoel"#username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: "rehanguha"
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: "rehanguha"
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
